"""Initial migration

Revision ID: 6a5a980c4a77
Revises: 
Create Date: 2026-08-20 18:37:21.333253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '6a5a980c4a77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunking_table', 'vector_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.drop_constraint(op.f('document_knowledge_base_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'knowledge_base', ['knowledge_base_id'], ['id'])
    op.drop_constraint(op.f('escalation_ticket_session_id_fkey'), 'escalation_ticket', type_='foreignkey')
    op.create_foreign_key(None, 'escalation_ticket', 'session_context', ['session_id'], ['id'])
    op.alter_column('guest', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('guest', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(op.f('hotel_chain_id_fkey'), 'hotel', type_='foreignkey')
    op.create_foreign_key(None, 'hotel', 'chain', ['chain_id'], ['id'])
    op.alter_column('intent_log', 'confidence_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.drop_constraint(op.f('intent_log_message_id_fkey'), 'intent_log', type_='foreignkey')
    op.create_foreign_key(None, 'intent_log', 'message_log', ['message_id'], ['id'])
    op.drop_constraint(op.f('knowledge_base_hotel_id_fkey'), 'knowledge_base', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_base', 'hotel', ['hotel_id'], ['id'])
    op.alter_column('message_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('message_log_session_id_fkey'), 'message_log', type_='foreignkey')
    op.create_foreign_key(None, 'message_log', 'session_context', ['session_id'], ['id'])
    op.alter_column('rag_citation', 'similarity_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False)
    op.drop_constraint(op.f('rag_citation_message_id_fkey'), 'rag_citation', type_='foreignkey')
    op.create_foreign_key(None, 'rag_citation', 'chunking_table', ['chunk_id'], ['id'])
    op.create_foreign_key(None, 'rag_citation', 'message_log', ['message_id'], ['id'])
    op.alter_column('room_booking', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('room_booking', 'check_in_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('room_booking', 'check_out_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(op.f('room_booking_guest_id_fkey'), 'room_booking', type_='foreignkey')
    op.drop_constraint(op.f('room_booking_session_id_fkey'), 'room_booking', type_='foreignkey')
    op.drop_constraint(op.f('room_booking_hotel_id_fkey'), 'room_booking', type_='foreignkey')
    op.create_foreign_key(None, 'room_booking', 'session_context', ['session_id'], ['id'])
    op.create_foreign_key(None, 'room_booking', 'hotel', ['hotel_id'], ['id'])
    op.create_foreign_key(None, 'room_booking', 'guest', ['guest_id'], ['id'])
    op.alter_column('session_context', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('session_context_hotel_id_fkey'), 'session_context', type_='foreignkey')
    op.drop_constraint(op.f('session_context_guest_id_fkey'), 'session_context', type_='foreignkey')
    op.create_foreign_key(None, 'session_context', 'guest', ['guest_id'], ['id'])
    op.create_foreign_key(None, 'session_context', 'hotel', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_context', type_='foreignkey')
    op.drop_constraint(None, 'session_context', type_='foreignkey')
    op.create_foreign_key(op.f('session_context_guest_id_fkey'), 'session_context', 'guest', ['guest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('session_context_hotel_id_fkey'), 'session_context', 'hotel', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('session_context', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'room_booking', type_='foreignkey')
    op.drop_constraint(None, 'room_booking', type_='foreignkey')
    op.drop_constraint(None, 'room_booking', type_='foreignkey')
    op.create_foreign_key(op.f('room_booking_hotel_id_fkey'), 'room_booking', 'hotel', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('room_booking_session_id_fkey'), 'room_booking', 'session_context', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('room_booking_guest_id_fkey'), 'room_booking', 'guest', ['guest_id'], ['id'], ondelete='CASCADE')
    op.alter_column('room_booking', 'check_out_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('room_booking', 'check_in_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('room_booking', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'rag_citation', type_='foreignkey')
    op.drop_constraint(None, 'rag_citation', type_='foreignkey')
    op.create_foreign_key(op.f('rag_citation_message_id_fkey'), 'rag_citation', 'message_log', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rag_citation', 'similarity_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.drop_constraint(None, 'message_log', type_='foreignkey')
    op.create_foreign_key(op.f('message_log_session_id_fkey'), 'message_log', 'session_context', ['session_id'], ['id'], ondelete='CASCADE')
    op.alter_column('message_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_base_hotel_id_fkey'), 'knowledge_base', 'hotel', ['hotel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'intent_log', type_='foreignkey')
    op.create_foreign_key(op.f('intent_log_message_id_fkey'), 'intent_log', 'message_log', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('intent_log', 'confidence_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True)
    op.drop_constraint(None, 'hotel', type_='foreignkey')
    op.create_foreign_key(op.f('hotel_chain_id_fkey'), 'hotel', 'chain', ['chain_id'], ['id'], ondelete='CASCADE')
    op.alter_column('guest', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('guest', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'escalation_ticket', type_='foreignkey')
    op.create_foreign_key(op.f('escalation_ticket_session_id_fkey'), 'escalation_ticket', 'session_context', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_knowledge_base_id_fkey'), 'document', 'knowledge_base', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chunking_table', 'vector_embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###
